name: Deploy to Production Server

# This action runs on every push to the 'main' branch
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "Connecting to server..."
          cd /home/srizon/network-device-monitoring
          echo "Pulling latest changes from git..."
          git pull
          echo "Restarting ndm.service..."
          sudo systemctl restart ndm.service
          echo "Deployment complete!"